// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Hash a PIN using Argon2id with secure parameters
String authHashPin({required String pin}) => RustLib.instance.api.crateApiAuthAuthHashPin(pin: pin);

/// Verify a PIN against stored Argon2 hash
bool authVerifyPin({required String pin, required String storedHash}) =>
    RustLib.instance.api.crateApiAuthAuthVerifyPin(pin: pin, storedHash: storedHash);

/// Generate a new TOTP secret (base32 encoded)
String authGenerate2FaSecret() => RustLib.instance.api.crateApiAuthAuthGenerate2FaSecret();

/// Verify a TOTP code against a secret (30-second window, +/- 1 step)
bool authVerify2FaCode({required String secret, required String code}) =>
    RustLib.instance.api.crateApiAuthAuthVerify2FaCode(secret: secret, code: code);
