// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WalletBalance {
  final String symbol;
  final String name;
  final double balance;
  final double usdValue;
  final bool isPrivacyCoin;

  const WalletBalance({
    required this.symbol,
    required this.name,
    required this.balance,
    required this.usdValue,
    required this.isPrivacyCoin,
  });
}

class WalletTransaction {
  final String id;
  final String txType;
  final String cryptoSymbol;
  final double amount;
  final int timestamp;
  final String? contactName;
  final String status;
  final String? txHash;

  const WalletTransaction({
    required this.id,
    required this.txType,
    required this.cryptoSymbol,
    required this.amount,
    required this.timestamp,
    this.contactName,
    required this.status,
    this.txHash,
  });
}

/// Generate a new 12-word BIP39 mnemonic
Future<String> walletGenerateMnemonic() =>
    RustLib.instance.api.crateApiWalletWalletGenerateMnemonic();

/// Validate and restore from BIP39 mnemonic
Future<bool> walletRestoreFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiWalletWalletRestoreFromMnemonic(mnemonic: mnemonic);

/// Get wallet balances for all supported currencies
Future<List<WalletBalance>> walletGetBalances({required String mnemonic}) =>
    RustLib.instance.api.crateApiWalletWalletGetBalances(mnemonic: mnemonic);

/// Generate receiving address for a currency
Future<String> walletGenerateAddress({
  required String mnemonic,
  required String currency,
  required int account,
}) =>
    RustLib.instance.api.crateApiWalletWalletGenerateAddress(
      mnemonic: mnemonic,
      currency: currency,
      account: account,
    );

/// Get transaction history for a currency
Future<List<WalletTransaction>> walletGetTransactions({
  required String mnemonic,
  required String currency,
}) =>
    RustLib.instance.api.crateApiWalletWalletGetTransactions(
      mnemonic: mnemonic,
      currency: currency,
    );
